spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/spring-study/spring-study/05-jpa_2_api_optim/jpashop/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create        # 애플리케이션 실행 시점에 (1) 가지고 있는 테이블 지우고 (2) 가진 엔티티 정보를 이용하여 테이블 다시 생성
    properties:
      hibernate:
        # show_sql: true        # sout으로 sql 찍기
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug  # logger로 sql 찍기
    org.hibernate.orm.jdbc.bind: trace  # 스프링 부트 3.x, hibernate6
